# Generated by Django 5.2.16 on 2026-07-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="albums.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "相册分类",
                "verbose_name_plural": "相册分类",
                "db_table": "category",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "cover",
                    models.URLField(blank=True, default="", verbose_name="封面图"),
                ),
                (
                    "homepage_show",
                    models.BooleanField(default=False, verbose_name="首页显示"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "photo_count",
                    models.IntegerField(default=0, verbose_name="图片数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="albums",
                        to="albums.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "相册",
                "verbose_name_plural": "相册",
                "db_table": "album",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="图片名称")),
                ("url", models.URLField(max_length=500, verbose_name="七牛云URL")),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小"),
                ),
                ("width", models.IntegerField(default=0, verbose_name="宽度")),
                ("height", models.IntegerField(default=0, verbose_name="高度")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="albums.album",
                        verbose_name="所属相册",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片",
                "verbose_name_plural": "图片",
                "db_table": "photo",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
