# Generated by Django 4.2.30 on 2026-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_disabled",
            field=models.BooleanField(default=False, verbose_name="禁用"),
        ),
    ]
